# Generated by Django 5.2.8 on 2025-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AddField(
            model_name='book',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
